services:
  fastapi:
    image: nfsr/fast-api-project:fastapi
    container_name: fastapi-container
    ports:
      - "${FAST_API_PORT}:8000"
    depends_on:
      - redis
      - mongodb
   
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - app_network
    volumes:
      - ./data:/data

  celery:
    image: nfsr/fast-api-project:fastapi
    container_name: celery-container
    depends_on:
      - redis
      - mongodb
   
    command: ["celery", "-A", "tasks.celery_app", "worker", "--loglevel=info"]
    networks:
      - app_network
    volumes:
      - ./data:/data

  redis:
    image: redis:7-alpine
    container_name: redis-container
    expose:
      - "6379"
    networks:
      - app_network

  mongodb:
    image: mongo:6.0
    container_name: mongodb-container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
    expose:
      - "27017"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
  data:
