name: Docker CI/CD
on:
  push:
    branches:
      - main
env:
  DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
  DOCKERHUB_REPOSITORY_NAME: fast-api-project
  # DEPLOYMENT_SERVER_IP: ${{ secrets.INSTANCE_IP }}


jobs:
  # build-and-push:
  #   runs-on: ubuntu-latest
  #   # needs: lint-check
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ env.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     - name: Docker meta
  #       id: meta
  #       uses: docker/metadata-action@v5
  #       with:
  #         images: |
  #           ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY_NAME }}
  #         tags: |
  #           type=sha,prefix=,suffix=
  #     - name: Build and push
  #       uses: docker/build-push-action@v6
  #       with:
  #         context: api
  #         push: true
  #         tags: ${{ steps.meta.outputs.tags }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push  
    steps:
      - uses: actions/checkout@v4
      - name: Transfer docker compose file to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.INSTANCE_IP }}
          username: ubuntu
          key: ${{ secrets.INSTANCE_RSA_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "/home/ubuntu"
      # - name: Deploy fast-api-project using docker compose
      #   uses: appleboy/ssh-action@v1.2.0
      #   with:
      #     host: ${{ secrets.INSTANCE_IP }}
      #     username: ubuntu
      #     key: ${{ secrets.INSTANCE_RSA_PRIVATE_KEY }}
      #     script: |
      #       export COMMIT_HASH=$(echo ${{ github.sha }} | cut -c1-7)
          