name: Python Code Tests

on:
  push:
    branches:
      - "feature/*"
  # pull_request:
  #   branches:
  #     - feature/test

permissions:
  contents: read

jobs:
  test-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          pip install --no-cache-dir -r app/requirements.txt
          pip install pytest

      - name: Unit Test
        run: |
          pytest app/tests/ 
